name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello!
        run: echo 'Hello from the pipeline'

  test-utils:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test utils
        run: npm run test-utils

  test-app:
    runs-on: ubuntu-latest
    steps:
        - name: Setup timezone
          uses: zcong1993/setup-timezone@master
          with:
           timezone: Europe/London
      - name: Checkout and clone repo
        uses: actions/checkout@v3
      - name: Setup PSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: test_db
          postgresql user: test_user
          postgresql password: password
      - name: Install dependencies
        run: npm ci
      - name: Test app
        run: PGDATABASE=test_db PGUSER=test_user PGPASSWORD=password npm run test-app --maxWorkers=1
    
  test-app-live-db:
    runs-on: ubuntu-latest
    steps:
      - name: Setup timezone
          uses: zcong1993/setup-timezone@master
          with:
           timezone: Europe/London
      - name: Checkout and clone repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci 
      - name: Test app against live database
        run: NODE_ENV=production DATABASE_URL=${{secrets.DATABASE_URL}} npm run test-app --maxWorkers=1